### ISSUE TITLE
Add a dry-run option

### ISSUE THREAD

**Issue by Weasy666** [Riscue/drone-kaniko#1]
Hey! Nice to see that someone took over this plugin.

Could you maybe add a `dry-run` option that adds `--no-push` to the kaniko command if present?  `plugins/docker` has it and it is really useful to test image builds?

**Comment by Riscue** [comment]
I added the dry-run option but couldn't test it.
Because my drone cloud account is disabled for no reason.
If you can test and got any bug, you always welcome to open a pr.
